### ISSUE TITLE
缺少这么多文件怎么破？OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory projects/GLEE/clip_vit_base_patch32.

### ISSUE THREAD

**Issue by yuukix77** [FoundationVision/GLEE#19]
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory projects/GLEE/clip_vit_base_patch32. 缺这么多文件怎么说

**Comment by wjf5203** [comment]
Thank you for bringing attention to the error message regarding the missing CLIP .bin weights. The requirement for this weights is indeed mentioned in our training documentation at https://github.com/FoundationVision/GLEE/blob/main/assets/TRAIN.md.

Understanding that not everyone will need to train the model, I have now updated our installation instructions to include this prompt. You can find the revised instructions at https://github.com/FoundationVision/GLEE/blob/main/assets/INSTALL.md.

Thanks for your reminder.
