### ISSUE TITLE
ImportError: cannot import name 'add_glee_config' from 'detectron2.projects'

### ISSUE THREAD

**Issue by skldjldhiqH** [FoundationVision/GLEE#33]
TEST.md, To inderence on COCO,在Plus上按命令运行时报错，ImportError: cannot import name 'add_glee_config' from 'detectron2.projects' (/root/miniconda3/envs/myconda/lib/python3.10/site-packages/detectron2-0.6-py3.10-linux-x86_64.egg/detectron2/projects/__init__.py)
重新下载了detectron2文件也不行，请问该怎么解决？

**Comment by yufu** [comment]
@skldjldhiqH  我遇到了同样 的问题，原因是detectron2 版本不对。不应该使用自己本来的版本，而应该使用INSTALL.md中pip3 install -e . 来安装。这个版本是作者更新后的，具有GLEE的config和函数
